#!/bin/bash

# Launcher for PT analysis binary (bin/analysis_pt)

SIZE=24
NT=20
NREP=4
NBINS=80
NTHREADS=$(nproc)

for arg in "$@"; do
    case "$arg" in
        --size=*)     SIZE="${arg#*=}" ;;
        --nt=*)       NT="${arg#*=}" ;;
        --nrep=*)     NREP="${arg#*=}" ;;
        --nbins=*)    NBINS="${arg#*=}" ;;
        --nthreads=*) NTHREADS="${arg#*=}" ;;
        --help)
            echo "Usage: $0 [OPTIONS]"
            echo "  --size=N      Number of spins (default: $SIZE)"
            echo "  --nt=NT       Number of temperatures (default: $NT)"
            echo "  --nrep=R      Number of replicas per temperature (default: $NREP)"
            echo "  --nbins=B     Number of bins for overlap histogram (default: $NBINS)"
            echo "  --nthreads=T  Threads for overlap computation (default: $(nproc))"
            exit 0
            ;;
        *)
            echo "Unknown option: $arg"
            exit 1
            ;;
    esac
done

./bin/analysis_pt -N "$SIZE" -NT "$NT" -nrep "$NREP" -nbins "$NBINS" -nthreads "$NTHREADS" --plot
